### PR TITLE
Make README readable on GitHub

### PR DESCRIPTION
**Pull request by satyaog**
Automate the generation process to avoid mistakes which could lead to incomplete / outdated READMEs

### CODE REVIEW

**Review by lebrice — APPROVED** [review]

**Review by obilaniu — APPROVED** [review]

**Comment by satyaog** [comment]
@btravouillon could you check if these are good?

* https://github.com/mila-iqia/mila-docs/pull/182/files#diff-b01f9374f6cc69f1d6b5f14f3c86dd1989076895b0d9d688f8fdddf35296acc6
* https://github.com/mila-iqia/mila-docs/pull/182/files#diff-e48b08a83a7077c916c8406b9d662387ea5d8b86143efa9735f5a144ee75034c

**Comment by lebrice** [comment]
Bump @btravouillon

**Comment by lebrice** [comment]
@satyaog can we merge this now?

**Comment by satyaog** [comment]
> The changes seem good. All checks have passed.
> 
> It is my understanding that the code is now duplicated in the READMEs, correct? The READMEs are updated during the pre-commit, right?

Yes the READMEs are updated during the pre-commit to contain a copy of the files normally referenced with a `literalinclude`

**Review by btravouillon — APPROVED** [review]
Looks good to me. 👍

**Pull request merged**
