### PR TITLE
Adding Cheat Sheet section

### PR DESCRIPTION
**Pull request by gyom**
Update for the Cheat Sheet section of the documentation.

We're missing the actual pdf, though, because I didn't want to upload a multitude of copies of the pdf. I'll upload the actual pdf in that branch when it's finalized in early September.

### CODE REVIEW

**Comment by satyaog** [comment]
@gyom I believe we have the pdf now? What would be missing from this PR to be merged?

**Comment by gyom** [comment]
@satyaog Thanks for the reminder. I do have the final pdf. I just need to get around to it, which I'll do in less than 24h.

**Comment by gyom** [comment]
Okay, so I've included the pdf now, but when I look at the build on Github it's not creating the link as I expected. It's probably just a minor thing that could be fixed by someone with better sphinx kung fu than me. I'd be thankful if someone else here solved it. @satyaog :)

**Review by btravouillon — APPROVED** [review]
Looks good to me. 👍

**Comment by satyaog** [comment]
We have an errata section but should we mention a communication channel for users to raise them to our attention? I suppose it would be it-support?

**Comment by btravouillon** [comment]
> We have an errata section but should we mention a communication channel for users to raise them to our attention? I suppose it would be it-support?

I would say one could refer to the first box **getting help**. ;)

**Comment by gyom** [comment]
When it-support creates the idt.cheatsheet@mila.quebec mailing list (conversation under way), I'll add it to docs.mila.quebec right away (in a different PR if needed).

**Review by satyaog — APPROVED** [review]
Approving and added #217 for the errata channel

**Pull request merged**
