### PR TITLE
Update FAQ with PyTorch 1.10 problem and quickfix

### PR DESCRIPTION
**Pull request by obilaniu**
Explain the PyTorch INTERNAL ASSERT FAILED at "../aten/src/ATen/MapAllocator.cpp":263 error and how to work around it.

Closes: #112

### CODE REVIEW

**Comment by obilaniu** [comment]
PR will close #112.

**Review by btravouillon — APPROVED** [review]
Looks good to me. 👍
We assume people know how to compile `hack.so`.

**Comment by obilaniu** [comment]
@btravouillon I have no idea how to distribute the binary or if it is even safe/advisable to do this.

**Comment by btravouillon** [comment]
> @btravouillon I have no idea how to distribute the binary or if it is even safe/advisable to do this.

We should not distribute the binary, people should know how to compile I guess. I just noticed the instructions to compile are in the gist. It's all good !

**Review by satyaog — APPROVED** [review]

**Pull request merged**
